import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Flex, Heading, Button, Card, Table, Badge, } from '@radix-ui/themes';
import { PlusIcon, TrashIcon } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
export default function ApiKeyManagementPage() {
    const navigate = useNavigate();
    const apiKeys = [];
    return (_jsx(Flex, { style: { minHeight: '100vh', background: 'var(--gray-50)' }, children: _jsxs(Box, { flexGrow: "1", p: "6", style: { maxWidth: 1200, margin: '0 auto' }, children: [_jsxs(Flex, { justify: "between", align: "center", mb: "5", children: [_jsx(Heading, { size: "5", children: "API Key Management" }), _jsxs(Button, { variant: "outline", size: "2", style: { gap: 4 }, children: [_jsx(PlusIcon, {}), " Generate Key"] })] }), _jsx(Card, { variant: "surface", size: "3", children: _jsxs(Table.Root, { children: [_jsx(Table.Header, { children: _jsxs(Table.Row, { children: [_jsx(Table.ColumnHeaderCell, { children: "Key Name" }), _jsx(Table.ColumnHeaderCell, { children: "Description" }), _jsx(Table.ColumnHeaderCell, { children: "Expires" }), _jsx(Table.ColumnHeaderCell, { children: "Created At" }), _jsx(Table.ColumnHeaderCell, { children: "Revoked" })] }) }), _jsx(Table.Body, { children: apiKeys?.map((key) => (_jsxs(Table.Row, { onClick: () => navigate(`/admin-center/api-keys/${key.id}`), style: { cursor: 'pointer' }, children: [_jsx(Table.Cell, { children: key.name }), _jsx(Table.Cell, { children: key.description?.slice(0, 10) ?? '—' }), _jsx(Table.Cell, { children: _jsx(Badge, { variant: "soft", color: key.expiresAt ? 'green' : 'gray', children: key.expiresAt ? key.expiresAt.toString().slice(0, 10) : 'Never' }) }), _jsx(Table.Cell, { children: key.createdAt.toString() }), _jsx(Table.Cell, { children: key.isRevoked }), _jsx(Table.Cell, { children: _jsx(Flex, { gap: "2", children: _jsx(Button, { variant: "ghost", size: "2", disabled: true, children: _jsx(TrashIcon, {}) }) }) })] }, key.id))) })] }) })] }) }));
}
