import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Card, Flex, Text } from "@radix-ui/themes";
import { SentimentChart } from "../components/SentimentChart";
import { ChannelChart } from "../components/ChannelChart";
import TopAccountList from "../components/TopAccountList";
import { DashboardHeader } from "../components/DashboardHeader";
import { MetricsTrends } from "../components/MetricsTrends";
export function Dashboard() {
    return (_jsxs(Box, { flexGrow: "1", p: "6", children: [_jsx(DashboardHeader, {}), _jsx(MetricsTrends, {}), _jsxs(Flex, { direction: "column", wrap: "wrap", children: [_jsx(Card, { style: { flex: 1, minWidth: 320 }, variant: "surface", size: "3", mb: "6", children: _jsx(SentimentChart, {}) }), _jsxs(Flex, { direction: "row", gap: "8", wrap: "wrap", children: [_jsxs(Card, { style: { flex: 1, minWidth: 320 }, variant: "surface", size: "3", mb: "6", children: [_jsx(Text, { size: "5", children: "Most used channels" }), _jsx(ChannelChart, {})] }), _jsxs(Card, { style: { flex: 1, minWidth: 320 }, variant: "surface", size: "3", mb: "6", children: [_jsx(Text, { size: "5", children: "Most mentioned Categories" }), _jsx(ChannelChart, {})] }), _jsxs(Card, { style: { flex: 1, minWidth: 320 }, variant: "surface", size: "3", mb: "6", children: [_jsx(Text, { size: "5", children: "Pain Points" }), _jsx(ChannelChart, {})] })] }), _jsxs(Flex, { direction: "row", gap: "8", wrap: "wrap", children: [_jsxs(Card, { style: { flex: 1 }, variant: "surface", size: "3", mb: "6", children: [_jsx(Text, { size: "5", children: "Most satisfied customers" }), _jsx(TopAccountList, {})] }), _jsxs(Card, { style: { flex: 1 }, variant: "surface", size: "3", mb: "6", children: [_jsx(Text, { size: "5", children: "Most dissatisfied customers" }), _jsx(TopAccountList, {})] })] }), _jsxs(Flex, { direction: "row", gap: "8", wrap: "wrap", children: [_jsxs(Card, { style: { flex: 1 }, variant: "surface", size: "3", mb: "6", children: [_jsx(Text, { size: "5", children: "Top rated categories" }), _jsx(TopAccountList, {})] }), _jsxs(Card, { style: { flex: 1 }, variant: "surface", size: "3", mb: "6", children: [_jsx(Text, { size: "5", children: "Worst rated categories" }), _jsx(TopAccountList, {})] })] })] })] }));
}
