import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Dashboard } from "./pages/Dashboard";
import AppLayout from "./components/AppLayout";
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import ContactsPage from "./pages/ContactsPage";
import AccountsPage from "./pages/AccountsPage";
import InteractionsPage from "./pages/InteractionsPage";
import { InteractionDetailPage } from "./pages/InteractionDetailPage";
import { AccountDetailPage } from "./pages/AccountDetailPage";
import { ContactDetailPage } from "./pages/ContactDetailPage";
import AnalyticsDashboard from "./components/AnalyticsDashboard";
import LoginPage from "./pages/LoginPage";
import RegisterPage from "./pages/RegisterPage";
import ResetPasswordPage from "./pages/ResetPasswordPage";
import SetNewPasswordPage from "./pages/SetNewPasswordPage";
import ResetPasswordConfirmationPage from "./pages/ResetPasswordConfirmationPage";
import { ProfilePage } from "./pages/ProfilePage";
import { UserPage } from "./pages/UserPage";
import AdminAppLayout from "./components/AdminAppLayout";
import ApiKeyManagementPage from "./pages/ApiManagementPage";
import ApiKeyDetail from "./pages/ApiKeyDetail";
import SignalsPage from "./pages/SignalsPage";
import SignalDetailPage from "./pages/SignalDetailPage";
import CategoryAnalysisPage from "./pages/CategoryAnalysisPage";
import JourneyAnalysisPage from "./pages/JourneyAnalysisPage";
import JourneyStepDetailPage from "./pages/JourneyStepDetailPage";
function App() {
    return (_jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/reset-password", element: _jsx(ResetPasswordPage, {}) }), _jsx(Route, { path: "/set-password", element: _jsx(SetNewPasswordPage, {}) }), _jsx(Route, { path: "/register", element: _jsx(RegisterPage, {}) }), _jsx(Route, { path: "/reset-confirmation", element: _jsx(ResetPasswordConfirmationPage, {}) }), _jsx(Route, { path: "/profile", element: _jsx(ProfilePage, {}) }), _jsxs(Route, { path: "/", element: _jsx(AppLayout, {}), children: [_jsx(Route, { index: true, path: "/", element: _jsx(Dashboard, {}) }), _jsx(Route, { path: "/signals", element: _jsx(SignalsPage, {}) }), _jsx(Route, { path: "/signals/:signalId", element: _jsx(SignalDetailPage, {}) }), _jsx(Route, { path: "/journey", element: _jsx(JourneyAnalysisPage, {}) }), _jsx(Route, { path: "/journey/:stepId", element: _jsx(JourneyStepDetailPage, {}) }), _jsx(Route, { path: "/website", element: _jsx(AnalyticsDashboard, {}) }), _jsx(Route, { path: "/contacts", element: _jsx(ContactsPage, {}) }), _jsx(Route, { path: "/contacts/:contactId", element: _jsx(ContactDetailPage, {}) }), _jsx(Route, { path: "/accounts", element: _jsx(AccountsPage, {}) }), _jsx(Route, { path: "/accounts/:accountId", element: _jsx(AccountDetailPage, {}) }), _jsx(Route, { path: "/interactions", element: _jsx(InteractionsPage, {}) }), _jsx(Route, { path: "/interactions/:interactionId", element: _jsx(InteractionDetailPage, {}) }), _jsx(Route, { path: "/categories", element: _jsx(CategoryAnalysisPage, {}) })] }), _jsxs(Route, { path: "/", element: _jsx(AdminAppLayout, {}), children: [_jsx(Route, { path: "admin/users", element: _jsx(UserPage, {}) }), _jsx(Route, { path: "admin/apikeys", element: _jsx(ApiKeyManagementPage, {}) }), _jsx(Route, { path: "admin/apikeys/:apiKeyId", element: _jsx(ApiKeyDetail, {}) })] })] }) }));
}
export default App;
