import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Table, Box, Flex, Heading, Text, Button, TextField, IconButton, Dialog, Select, } from '@radix-ui/themes';
import { PlusIcon, SearchIcon, TrashIcon } from 'lucide-react';
import { useTranslation } from "react-i18next";
export function InvitationList() {
    const { t } = useTranslation();
    const [inviteOpen, setInviteOpen] = useState(false);
    const [newName, setNewName] = useState('');
    const [newEmail, setNewEmail] = useState('');
    const [newRole, setNewRole] = useState('member');
    const [search, setSearch] = useState('');
    const filtered = [];
    return (_jsx(Flex, { children: _jsxs(Box, { flexGrow: "1", p: "6", children: [_jsxs(Flex, { justify: "between", align: "center", mb: "5", children: [_jsx(Heading, { mb: "4", children: t('sidebar.users') }), _jsxs(Dialog.Root, { children: [_jsx(Dialog.Trigger, { children: _jsxs(Button, { children: [_jsx(PlusIcon, {}), " ", t('userList.inviteUser')] }) }), _jsxs(Dialog.Content, { maxWidth: "450px", children: [_jsx(Dialog.Title, { children: "Invite User" }), _jsx(Dialog.Description, { size: "2", mb: "4", children: t('userList.inviteHint') }), _jsx(Text, { as: "div", size: "2", mb: "1", weight: "bold", children: t('user.email') }), _jsx(TextField.Root, { placeholder: "email address", value: newEmail, onChange: (e) => setNewEmail(e.target.value) }), _jsx(Text, { as: "div", size: "2", mb: "1", weight: "bold", children: t('user.role') }), _jsx(Flex, { direction: "column", gap: "1", style: { marginBottom: "15px" }, children: _jsxs(Select.Root, { defaultValue: "member", value: newRole, onValueChange: (e) => setNewRole(e), children: [_jsx(Select.Trigger, {}), _jsxs(Select.Content, { children: [_jsx(Select.Item, { value: "member", children: "Member" }), _jsx(Select.Item, { value: "admin", children: "Admin" })] })] }) }), _jsxs(Flex, { gap: "3", mt: "4", justify: "between", children: [_jsx(Dialog.Close, { children: _jsx(Button, { variant: "soft", color: "gray", children: t('general.cancel') }) }), _jsx(Button, { children: t('general.submit') })] })] })] })] }), _jsx(Flex, { mb: "4", children: _jsx(TextField.Root, { placeholder: t('userList.searchUser'), value: search, onChange: (e) => setSearch(e.target.value), style: { flex: 1, padding: '8px 12px', borderRadius: 6, border: '1px solid var(--gray-200)' }, children: _jsx(TextField.Slot, { children: _jsx(SearchIcon, { height: "16", width: "16" }) }) }) }), _jsxs(Table.Root, { children: [_jsx(Table.Header, { children: _jsxs(Table.Row, { children: [_jsx(Table.ColumnHeaderCell, { children: t('user.email') }), _jsx(Table.ColumnHeaderCell, { children: t('user.role') }), _jsx(Table.ColumnHeaderCell, {})] }) }), _jsx(Table.Body, { children: filtered?.map((c) => (_jsxs(Table.Row, { style: { cursor: 'pointer' }, children: [_jsx(Table.Cell, { children: c.email }), _jsx(Table.Cell, { children: c.role }), _jsx(Table.Cell, { children: _jsx(IconButton, { variant: "ghost", children: _jsx(TrashIcon, {}) }) })] }, c.invitationCode))) })] })] }) }));
}
